# Base Information
group_name: "OpenStudioLandscapes_OpenCue_Worker"
key_prefixes:
  - "OpenStudioLandscapes_OpenCue_Worker"

#compose_scope: "worker"

#enabled: false

#ENV_VAR_PORT_HOST: 1234
#ENV_VAR_PORT_CONTAINER: 2345

#MOUNTED_VOLUME: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/volume"
